mensaje_de_error=[
        "1",
        " debe ir seguido de un numero",
        " el identificador debe ir seguido de ' = ' ",
        " 4",
        " falta una coma",
        " se esperaba un 'rango'",
        " el identificador debe ser tipo num",
        "simbolo incorrecto detras de las instrucciones de un bloque",
        "se espera un punto",
        "falta un punto y coma entre instrucciones",
        "identificador no declarado",
        "no estan permitidas las asignaciones a constantes o procedimientos",
        "se esperaba el operador de asignacion",
        "CALL debe de ir seguido de un identificador",
        "no tiene sentido llamar a una constante o a una variable",
        "se espera un THEN",
        "se espera un END o un punto y coma",
        "se espera un DO",
        "un simbolo incorrecto sigue a una instruccion",
        "se esperaba un operador relacional",
        "una expresion no debe de contener un identificador de procedimiento",
        " falta un parentesis de cierre",
        "el factor anterior no puede ir seguido de este simbolo o falta un punto y coma",
        "una expresion no puede empezar con este simbolo",
        " debe ir seguido de un '('",
        " debe ir seguido de una '{'",
        " falta una llave de cierre '}'",
        "",
        "",
        "este numero es demasiado grande - trunc(5)",
        "se rebaso el tamaño de la Tabla de Simbolos",
        "el programa fuente esta incompleto",
        "el programa fuente es demasiado largo",
        "anidamiento demasiado profundo para los procedures",
        "se rebasa el maximo entero de cpiton--se asume cero"]

